batch_size: 4
conv_name: highresnet
data_name: hc_pediatric_stem_ventricle_highresnet_f0
epoch_num: 400
exp_name: hc_pediatric_stem_ventricle_highresnet_f0
fold_name: 0
h_size: 128
lr: 0.01
momentum: 0.5
num_workers: 8
opt_gamma: 0.5
opt_step: 80
patching: Resize
print_freq: 1
root: ./bbox/
task_name: all
test_freq: 80
w_size: 128
weight_decay: 5.0e-05
z_size: 64
